apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata: 
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on
        # ErrImagePull (No se pudo encontrar la imagen en internet)
        # Tomar la imagen local
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  # type: NodePort
# Will be ClusterIP
  selector:
    app: backend # POds que cumplan con este label
  ports:
    - protocol: TCP
      port: 80
      # In pods
      targetPort: 9090
    # - containerPort: 9090.

# Se debe ver el pod qeu esta resolviendo el servicio, es decir se esta haciendo la solicitud por el puerto 80.
# Cuando se hace esto, el servicio lo envia a un pod en el puerto 9090 y ese pod regresa la informacion con la hora.