apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata: 
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on
        # ErrImagePull (No se pudo encontrar la imagen en internet)
        # Tomar la imagen local
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30080  # Puerto accesible desde el host
